### ISSUE TITLE
cannot boot some of the installed iso's

### ISSUE THREAD

**Issue by alexxtasi** [mbusb/multibootusb#95] opened 2017-02-02 15:11 UTC
Hi and thanks for multibootusb!

strange but although it works fine, some of the iso's I have installed do strange things

[SystemRescueCD 4.9.2](http://www.system-rescue-cd.org) and [Clonezilla](http://clonezilla.org/) live do work fine, but : 

- [lubuntu 16.10](http://lubuntu.net/)
- [ubuntu 16.04](http://releases.ubuntu.com/16.04/) and
- [ubuntu 12.04](http://ts.sch.gr/repo/livecd/ubuntu-12.04.3-desktop-i386-sch.iso) (this version I have to use frequently due to work requirements)

cannot boot.
The first two just hangs with a black screen and then reboot.
The last one after a while (showing the ubuntu logo) goes to this message:
```
BusyBox v1.18.5 (ubuntu 1:1.18.5-1ubuntu4.1) built-in shell (ash)
Enter 'help' for a list of built-in commands.

(initramfs) Unable to find a medium containing a live file system
```

I am sure all three iso's are correct (md5sum checked) and also the work when I create a startup usb with each one.
I am using multibootusb version 8.4.0 on ubuntu-gnome 16.04.01
regards

**Comment by mbusb** [comment] 2017-02-03 01:35
Can you zip isolinux directory of each distro and upload.

**Comment by alexxtasi** [comment] 2017-02-03 10:30
I zipped in 7z isolinux directory of ubuntu 16.04 and 12.04 (I had uninstalled the lubuntu iso while testing but I will install it again and compress... in a while).
Where to upload them ? I can't see an option here in...

**Comment by mbusb** [comment] 2017-02-03 11:21
You can send me through email.

**Comment by alexxtasi** [comment] 2017-02-03 11:58
google blocked my email cause of the attachments !!
so I uploaded the two zip files on my google drive and these are the links to them:

[isolinux_ubuntu-12.04-sch.zip](https://drive.google.com/open?id=0B2iyk-4qnTaTWDdyVnBIeER1X1lJckhxM2NEdnMzTWdhQjdJ)
[isolinux_ubuntu-16.04.zip](https://drive.google.com/open?id=0B2iyk-4qnTaTaHUxaFdCd1RoazMxS282M2pFMm90dnZhTTdZ)

please confirm the download on your side

**Comment by mbusb** [comment] 2017-02-03 15:49
Thanks. I have looked at files forwarded by you. I had lubuntu 16.10 ISO and tested it to reproduce the issue at my side. Surpricingly, there is no issue I could find at my side. Here is the look at your file 'txt.cfg' for ubuntu 16.04:-

```
label live
  menu label ^Try Ubuntu without installing
  kernel /multibootusb/ubuntu-16.04-desktop-i386/casper/vmlinuz
  append  file=/multibootusb/ubuntu-16.04-desktop-i386/cdrom/preseed/ubuntu.seed boot=casper initrd=/multibootusb/ubuntu-16.04-desktop-i386/casper/initrd.lz quiet splash ---
```

and here is my file (based on 16.10):-

```
label live
  menu label ^Try Lubuntu without installing
  kernel /multibootusb/lubuntu-16.10-desktop-amd64/casper/vmlinuz.efi
  append  file=/multibootusb/lubuntu-16.10-desktop-amd64/cdrom/preseed/lubuntu.seed boot=casper cdrom-detect/try-usb=true floppy.allowed_drive_mask=0 ignore_uuid ignore_bootid root=UUID=5402-857F live-media-path=/multibootusb/lubuntu-16.10-desktop-amd64/casper initrd=/multibootusb/lubuntu-16.10-desktop-amd64/casper/initrd.lz quiet splash ---
```
Now you can see the differences. The only thing you need to modify here is to add **live-media-path=/multibootusb/lubuntu-16.10-desktop-amd64/casper**  parameter to your *.cfg files (somewhere close to **initrd=** parameter).

Can you reproduce the issue again and post the terminal output or send log file.

**Comment by alexxtasi** [comment] 2017-02-03 17:12
1. I created the lubuntu (amd64) iso and finally uploaded the isolinux directory on GoogleDrive [isolinux_lubuntu-16.10-amd64.zip](https://drive.google.com/open?id=0B2iyk-4qnTaTTGI2QURQS2I0bVU). I can see some differences in txt.cfg file compared to your post above !! (there is also no ```live-media-path``` param nor those ```cdrom-detect``` etc)

2. adding `live-media-path=/multibootusb/lubuntu-16.10-desktop-amd64/casper` to txt.cfg so a part of the file is like:
```
label live
  menu label ^Try Lubuntu without installing
  kernel /multibootusb/lubuntu-16.10-desktop-amd64/casper/vmlinuz.efi
  append  file=/multibootusb/lubuntu-16.10-desktop-amd64/cdrom/preseed/lubuntu.seed boot=casper live-media-path=/multibootusb/lubuntu-16.10-desktop-amd64/casper initrd=/multibootusb/lubuntu-16.10-desktop-amd64/casper/initrd.lz quiet splash ---
```
has no success on boot (goes to restart)

3. > Can you reproduce the issue again and post the terminal output or send log file.

how can I do that ? Should I run multibootusb from terminal ? Where can I find it's log files ?

regards

**Comment by mbusb** [comment] 2017-02-04 00:08
Look at the this link to changelog
https://github.com/mbusb/multibootusb/blob/master/CHANGELOG . Log file
location is mentioned under version 8.4.0.

**Comment by alexxtasi** [comment] 2017-02-06 16:55
Lets separate things and take account of the ubuntu 16.04 iso firstly.
I did the following

- uninstalled all problematic iso's and left only those I could but into (systemrescuecd and clonezilla)
- installed ubuntu-16.04-desktop-i386.iso (downloaded from [here](http://releases.ubuntu.com/16.04/))

You can find the multibootusb's log file [here](https://drive.google.com/open?id=0B2iyk-4qnTaTZ0pyMTFYaEZUY0k) and the compressed isolinux directory generated [here](https://drive.google.com/open?id=0B2iyk-4qnTaTRW5DTU82MENFNE0)

Trying to boot to ubuntu 16.04 I see this on screen:
```
SYSLINUX 6.03 EDD 6.03* Copyright (C) 1994-2014 H.Peter Anvin et al
Loading boot logo...
```
and then the machine reboots!!

The txt.cfg file (the `label live` part) as you can see has these contents:
```
label live
  menu label ^Try Ubuntu without installing
  kernel /multibootusb/ubuntu-16.04-desktop-i386/casper/vmlinuz
  append  file=/multibootusb/ubuntu-16.04-desktop-i386/cdrom/preseed/ubuntu.seed boot=casper initrd=/multibootusb/ubuntu-16.04-desktop-i386/casper/initrd.lz quiet splash ---
```

should I do the same with other iso's I found problems and provide you logs or just wait this ?
regards

**Comment by mbusb** [comment] 2017-02-06 17:11
Ha, found where the problem lies. The ISO file (ubuntu) is detected as a debian ISO. That too detected as a Debian net install. That is the reason why your 'cfg' files also not updated as expected. I need to figure out why does this happen and do some bug fix.

**Comment by alexxtasi** [comment] 2017-02-06 17:24
Good news!!!
Should I do the same and provide you logs for other iso's I am interesting in ?
- [ubuntu 12.04 sch](http://ts.sch.gr/wiki/Linux/LiveCD)
- [lubuntu 16.10 i386](http://cdimage.ubuntu.com/lubuntu/releases/16.10/release/) (and 64bit as well)
- [inquisitor v3.0](http://www.inquisitor.ru/download.html)

(In those I had similar problems too)
or .... one at a time ?

**Comment by mbusb** [comment] 2017-02-06 17:24
Please upload. Will see through it.

**Comment by mbusb** [comment] 2017-02-06 17:29
Just made a commit to master. Can you download the master source code and check if it works properly?

**Comment by alexxtasi** [comment] 2017-02-06 17:40
I am not an expert in git ;-) so correct me if wrong. I did:
- `git clone ...` in a directory
- follow the [How to install ? ](https://github.com/mbusb/multibootusb#how-to-install) section of the  README.md
(should I have to uninstall multibootusb prior ?)

I 'll repeat the ubuntu-16.04 steps and come back

**Comment by alexxtasi** [comment] 2017-02-06 18:05
log file is [here](https://drive.google.com/open?id=0B2iyk-4qnTaTX0FweW41Vk0xa2c) and here is the compressed [isolinux](https://drive.google.com/open?id=0B2iyk-4qnTaTWkV3ZTVQS21kOFk) 
and yes it works !!! (inside the qemu at least :-) )
I will try with the other iso's I was talking about and report

**Comment by mbusb** [comment] 2017-02-06 18:06
No need to install it again. Simply download from this link https://codeload.github.com/mbusb/multibootusb/zip/master and extract to local disk. Move in to the extracted directory and issue the command 'sudo python3 ./multibootusb' (without quote).

**Comment by mbusb** [comment] 2017-02-06 18:08
Saw the log file. It should work on real hardware as well. Will release it as new version in next few days.

**Comment by alexxtasi** [comment] 2017-02-06 19:38
I tested other iso's and all where successful except [inquisitor v3.0](http://www.inquisitor.ru/download.html)
Here you can find:
- [log file](https://drive.google.com/open?id=0B2iyk-4qnTaTU1RablRuOHhCTGM)
- [terminal output](https://drive.google.com/open?id=0B2iyk-4qnTaTcXM3b19BcVhYcmc)
- [created directory inside multibootusb dir](https://drive.google.com/open?id=0B2iyk-4qnTaTODNUbWFDZUF1YVU) (strange there is only this and the iso provided lies outside the multibootusb directory ! )

The ubuntu 12.04 - sch iso works fine except when choosing `Install` it goes directly to `live cd`. But this is not a big deal (this is a very old version and the live cd suits me fine)

**Comment by Dizirgee** [comment] 2017-02-25 23:07
Hello, there appears to be issue with latest antergos iso (antergos-17.2-x86_64.iso) , image is written to USB but it fails to boot, both in qemu and real boot:
`Could not find kernel image: /multibootusb/antergos/%INSTALL_DIR%/boot/vmlinuz`
correct path [whats on USB] should be
`/multibootusb/antergos/arch/boot/vmlinuz` 
[pic](http://imgur.com/a/WC8TM)
not sure from where that %INSTALL_DIR% is coming from, I tried to look through some .cfg files but I didn't find anything. In J:\multibootusb\syslinux.cfg 
`MENU LABEL antergos`
`BOOT /multibootusb/antergos/arch/boot/syslinux/isolinux/arch.bs`
and looking into J:\multibootusb\antergos\isolinux\isolinux.cfg all appears to be ok, not sure where else to look
`label start`
`kernel /multibootusb/antergos/arch/boot/vmlinuz`
originally it was "antergos-17.2-x86_64" but I renamed .iso just to antergos to see if there isn't issue with some chars or long name, though manjaro and solus works fine.

btw manual boot [by typing correct path to vmlinuz] doesn't work, it hangs in qemu shortly after and in real boot it goes to kernel panic and hangs. Iso image itself should be fine because it can boot in VM

and thanks for the tool

**Comment by alexxtasi** [comment] 2017-03-31 13:26
@mbusb : any clue with the above inquisitor v3.0 ??
should I sent you reports here for other iso's also ? (I intent to create a usb with bootalbe iso's I use...)

**Comment by alindt** [comment] 2017-04-23 21:07
Give the [latest release](https://github.com/mbusb/multibootusb/releases) (8.6.0) a try

**Comment by mbusb** [comment] 2017-04-30 10:38
@alexxtasi , the issue is not relevant to the actual question. Any way I will try. closing the issue now.

**Closed by mbusb** 2017-04-30 10:38 UTC

**Comment by genbtc** [comment] 2017-08-24 05:05
Hi. I am in the same situation as "Dizirgee" who commented on Feb 25. 
antergos-17.7-x86_64.iso  "Antergos Linux"
It is complaining about %INSTALL_DIR% and i searched for that string in the contents of the whole drive, and i found it was ONLY in  F:\multibootusb\antergos-17.7-x86_64\isolinux\bootlogo (28 hits) 
Now bootlogo is a 3.7mb file with all kinds of stuff thrown in it, images, code, syslinux stuff. It seems like Antergos devs are putting non-standard stuff in the bootlogo file and its tricking this program.

**Comment by genbtc** [comment] 2017-08-24 06:14
This is what ended up working for me:
```
#start antergos-17.7-x86_64
LABEL antergos-17.7-x86_64
MENU LABEL antergos-17.7-x86_64
kernel /multibootusb/antergos-17.7-x86_64/arch/boot/vmlinuz
append initrd=/multibootusb/antergos-17.7-x86_64/arch/boot/intel_ucode.img,/multibootusb/antergos-17.7-x86_64/arch/boot/archiso.img archisobasedir=multibootusb/antergos-17.7-x86_64/arch archisodevice=/dev/disk/by-uuid/D942-948F earlymodules=loop modules-load=loop rd.modules-load=loop udev.log-priority=crit rd.udev.log-priority=crit quiet splash
#end antergos-17.7-x86_64
```
As my main entry for it in @ F:\multibootusb\syslinux.cfg 
This will just use the syslinux we are already in and get right into it. The command was generated by the program correctly, because I got it out of the multiboot "conf" config dirs.
