### ISSUE TITLE
Installing syslinux crashes with 9.1.0-1 (Linux Mint 18.3 host)

### ISSUE THREAD

**Issue by Kassec** [mbusb/multibootusb#268] opened 2018-02-22 11:16 UTC
Hello,

Trying to install syslinux to USB stick crashes : 
```
$ sudo multibootusb
Running multibootusb version 9.1.0 from installed system...
Starting multibootusb GUI...
Cleaning old multibootusb directory...
Syslinux exist in multibootusb directory...
Using pyudev for detecting USB drives...
	/dev/sdc
	/dev/sdc1
Selected device /dev/sdc
USB disk is not mounted and can't update list widget...
Selected device /dev/sdc1
Installing default syslinux on /dev/sdc1
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 364, in onInstall_syslinuxClick
    ret = syslinux_default(config.usb_disk)
  File "/usr/lib/python3/dist-packages/scripts/syslinux.py", line 108, in syslinux_default
    mbr_install_cmd = 'dd bs=440 count=1 conv=notrunc if=' + mbr_bin + ' of=' + usb_disk[:-1]
TypeError: Can't convert 'bool' object to str implicitly
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.3 Sylvia
Release:	18.3
Codename:	sylvia
```

**Comment by mbusb** [comment] 2018-03-11 03:33
I think the issue is addressed in the latest master. You may wantto check  it out.

**Comment by mbusb** [comment] 2018-03-11 15:59
@shinji-s ,
The non English local issue affect only Windows version. The bug reported here is a real issue.

**Comment by shinji-s** [comment] 2018-03-11 18:14
@mbusb,
Thank you for the heads up. I paid attention to the exception log part only.
The cause may be the same: Failure to determine partition type of the target usb.
After "Selected device /dev/sdc1" should not we see the detected partition type printed?
Perhaps parted is not installed or not found in PATH?
@Kassec, 
Can you see what happens if you do "sudo parted /dev/sdc print" or better yet try logging '_cmd_out' in gpt_device@scripts/usb.py?

**Comment by shinji-s** [comment] 2018-03-11 18:44
Ah, parted is run against a partition (/dev/sdc1) rather than the entire disk (/dev/sdc). Is it reporting 'loop' as the partition type?
Perhaps same issue as https://github.com/mbusb/multibootusb/issues/265. Evident on Fedora?

**Comment by mbusb** [comment] 2018-03-13 17:33
The issue has been fixed in the devel and master branch. Should not occur in next release.

**Comment by mbusb** [comment] 2018-04-05 18:04
Try latest release. Fixed it.

**Closed by mbusb** 2018-04-05 18:04 UTC
