### ISSUE TITLE
Boot ISO not working

### ISSUE THREAD

**Issue by fadelm0** [mbusb/multibootusb#68] opened 2016-11-17 10:52 UTC
I am on windows 7 x64, running mbusb v8.0.

When I choose an ISO image and click Boot ISO, nothing happens. I have tried other software that include the same function and they all work.

**Comment by mbusb** [comment] 2016-11-20 12:21
I am unable to reproduce your issue on my system with same configuration. All works fine here.

Are you getting any king of feedback? Can you try and tell me if the same issue persist in latest version?

**Comment by fadelm0** [comment] 2016-11-20 22:08
Nope, no kind of feedback at all. I just choose the ram size, load up the path to the ISO file, and hit boot ISO. The only thing that happens is the path to the file disappears in the field, and that's about it.

I tried several different ISOs of course, and I tried the latest version of mbu. The same issue persists.

I don't even know how to provide more info on this, if you say you can't reproduce it. Can it spit out a log or something that might help?

**Comment by mbusb** [comment] 2016-12-03 09:33
Seems like you are selecting a memory size which is not allowed by the OS. Unfortunately qemu does not produce any error for this. Try to reproduce the same with lesser memory and report back.

**Comment by fadelm0** [comment] 2016-12-10 13:30
No no, this happens no matter what memory size I select.

Actually, I just found the problem today. If the file path to the image file contains any spaces, mbusb just refuses to start it, without giving any warnings. I tried putting the image file in any root folder and it booted just fine.

**Comment by mbusb** [comment] 2016-12-10 21:37
That shouldn't be a problem. I will fix it immediately.

**Comment by mbusb** [comment] 2016-12-26 18:20
Fixed in the latest release. Should work now.

**Closed by mbusb** 2016-12-26 18:20 UTC
