### ISSUE TITLE
Doesn't start on windows

### ISSUE THREAD

**Issue by Dam4rusxp** [mbusb/multibootusb#243] opened 2017-12-05 02:23 UTC
Version 8.9.0 doesn't open on windows, while 8.8.0 does.

Here's a log of me trying to start a few times in version 8.9.0:
```
03:01:31.897 root INFO Running multibootusb version 8.9.0 from installed system...
03:01:31.938 root INFO Starting multibootusb GUI...
03:01:32.018 root INFO Extracting syslinux to multibootusb directory...
03:01:32.099 root INFO Extracting syslinux modules to multibootusb directory...
03:01:32.981 root INFO Selected device E:
03:01:53.052 root INFO Running multibootusb version 8.9.0 from installed system...
03:01:53.090 root INFO Starting multibootusb GUI...
03:01:53.125 root INFO Cleaning old multibootusb directory...
03:01:53.128 root INFO Extracting syslinux to multibootusb directory...
03:01:53.189 root INFO Extracting syslinux modules to multibootusb directory...
03:01:53.708 root INFO Selected device E:
03:03:36.420 root INFO Running multibootusb version 8.9.0 from installed system...
03:03:36.459 root INFO Starting multibootusb GUI...
03:03:36.495 root INFO Cleaning old multibootusb directory...
03:03:36.499 root INFO Extracting syslinux to multibootusb directory...
03:03:36.563 root INFO Extracting syslinux modules to multibootusb directory...
03:03:37.128 root INFO Selected device E:
03:03:44.549 root INFO Running multibootusb version 8.9.0 from installed system...
03:03:44.590 root INFO Starting multibootusb GUI...
03:03:44.624 root INFO Cleaning old multibootusb directory...
03:03:44.627 root INFO Extracting syslinux to multibootusb directory...
03:03:44.687 root INFO Extracting syslinux modules to multibootusb directory...
03:03:45.219 root INFO Selected device E:
```

**Comment by mbusb** [comment] 2017-12-05 04:55
Can you tell me the system language? I suspect that the issue is with
language.

**Comment by Dam4rusxp** [comment] 2017-12-05 11:10
I'm using a German Windows 10 Pro.

**Comment by sudwebdesign** [comment] 2017-12-11 01:05
In Windows XP SP3 (French) have this error
![multibootusb-8.9.0-setup.exe after great install ;) Bug when is launched](http://sudwebdesign.free.fr/data/medias/bugs/multibootusb-8.9.0-setup.exe_after_install_OK_and_launched.jpg)

**Comment by mbusb** [comment] 2017-12-14 07:43
The fix has been committed in the master branch. Will release the new
version soon.

**Comment by mbusb** [comment] 2018-01-01 16:38
Please [download](https://drive.google.com/open?id=1pBQNMbuLuvJwQ7q5nvThg1VpfKjOfmTc) the yet to be released setup file. If you can confirm that it fixes the issue then I will go ahead and release it to public download.

**Comment by cookwu** [comment] 2018-01-02 08:35
After installing distro to usb, multibootusb shutdown itself and could not recognize any installed distros after restart the software.

**Comment by mbusb** [comment] 2018-01-02 11:22
Which distro did you install? Where is your log file?

**Comment by mbusb** [comment] 2018-01-07 06:17
The new release fixes the original issue of first post. Closing the issue.

**Closed by mbusb** 2018-01-07 06:17 UTC
