### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by haary** [mbusb/multibootusb#217] opened 2017-10-23 13:44 UTC
I installed the newest master with fix #180 because I suffered from the same issue (/dev/sdb is occupied by card reader).  Now I get the error  

```

Running multibootusb version 8.8.0 from installed system...
Starting multibootusb GUI...
Cleaning old multibootusb directory...
Syslinux exist in multibootusb directory...
Using pyudev for detecting USB drives...
        /dev/sdb
Selected device /dev/sdb
fdisk: cannot open /dev/sdb: Kein Medium gefunden
ERROR: fdisk failed on disk/partition (/dev/sdb)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/scripts/mbusb_gui.py", line 150, in onComboChange
    config.persistence_max_size = persistence.max_disk_persistence(config.usb_disk)
  File "/usr/local/lib/python3.5/dist-packages/scripts/persistence.py", line 27, in max_disk_persistence
    config.usb_uuid = usb_details['uuid']
TypeError: 'NoneType' object is not subscriptable
Abgebrochen

```

**Comment by mbusb** [comment] 2017-10-24 05:31
What happens when you use fdisk command directly on terminal for the same card reader?

**Comment by haary** [comment] 2017-10-24 08:38
Since there is no media inside the same as in the error messsage. However, I think this isn't the issue here since the fdisk error was fixed with #180 - but this fix triggered the error "'NoneType' object is not subscriptable".  "NoneType" is the type for the None object, which is an object that indicates no value. This makes sense, because /dev/sdb doesn't really exist, so there are no values available for this device.

**Comment by malkavi** [comment] 2017-10-24 16:21
I have the same issue, i am using multibootusb with the Fix #180 
```
Using pyudev for detecting USB drives...
        /dev/sdb
        /dev/sdc
        /dev/sdd
        /dev/sde
Selected device /dev/sdb
/bin/sh: fdisk: no se encontró la orden
ERROR: fdisk failed on disk/partition (/dev/sdb)
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/scripts/mbusb_gui.py", line 149, in onComboChange
    config.persistence_max_size = persistence.max_disk_persistence(config.usb_disk)
  File "/usr/lib/python3.4/site-packages/scripts/persistence.py", line 27, in max_disk_persistence
    config.usb_uuid = usb_details['uuid']
TypeError: 'NoneType' object is not subscriptable
Abortado (`core' generado)
```

**Comment by alandmoore** [comment] 2017-10-24 16:36
I have a card reader with no media installed, but I can't reproduce this.  Are you running multibootusb with any switches or arguments?  Do you have other valid devices plugged in?

Does it happen on launch or while selecting options?

**Comment by mbusb** [comment] 2017-10-24 16:49
Just to rule out the possible mistake, can you confirm that you run the
program with sudo or root privilege?

**Comment by malkavi** [comment] 2017-10-24 16:53
I'm running multibootusb without arguments.
I have an embedded multi-card reader, without any media.
With or without an usb plugged, I have the same output launching.
```
linux-g4fj:/home/malkavi # multibootusb -d
=== DEBUG ENABLED ===
Running multibootusb version 8.8.0 from installed system...
Starting multibootusb GUI...
Cleaning old multibootusb directory...
Syslinux exist in multibootusb directory...
Using pyudev for detecting USB drives...
        /dev/sdf
        /dev/sdf1
        /dev/sdb
        /dev/sdc
        /dev/sdd
        /dev/sde
Selected device /dev/sdb
fdisk: no se puede abrir /dev/sdb: No se ha encontrado el medio
ERROR: fdisk failed on disk/partition (/dev/sdb)
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/scripts/mbusb_gui.py", line 149, in onComboChange
    config.persistence_max_size = persistence.max_disk_persistence(config.usb_disk)
  File "/usr/lib/python3.4/site-packages/scripts/persistence.py", line 27, in max_disk_persistence
    config.usb_uuid = usb_details['uuid']
TypeError: 'NoneType' object is not subscriptable
Abortado (`core' generado)

```

**Comment by haary** [comment] 2017-10-24 17:03
Yes, I run the program with no arguments with root privileges. It happens on launch, with or without any devices plugged in. I am not able to launch the program. For verification, I disconnected the internal card reader from the motherboard and then multibootusb launches and works without problems so far.

**Comment by alandmoore** [comment] 2017-10-24 17:08
Can one of you with the bug plug in your card reader and provide the output of this code from a python interpreter:

```
import pyudev
context = pyudev.Context()
devices = context.list_devices(subsystem='block')
for device in devices:
    print(device.get('DEVNAME'), device.get('ID_BUS'), device.get('ID_PART_TABLE_TYPE'))
```

It seems to me the only way this can happen is if you have a device which is showing a non-falsey value for `ID_PART_TABLE_TYPE` (so that it gets listed as a valid partition), but then fails `fdisk`.

**Comment by malkavi** [comment] 2017-10-24 17:28
Output:
```
/dev/sdb usb None
/dev/sdc usb None
/dev/sdd usb None
/dev/sde usb None
/dev/sda ata gpt
/dev/sda1 ata gpt
/dev/sda2 ata gpt
/dev/sda3 ata gpt
/dev/sda5 ata gpt
/dev/sda6 ata gpt
/dev/sda7 ata gpt
/dev/sr0 ata None
/dev/nvme0n1 None gpt
/dev/nvme0n1p1 None gpt
/dev/nvme0n1p2 None gpt
/dev/nvme0n1p3 None gpt
/dev/nvme0n1p4 None gpt
/dev/nvme0n1p5 None gpt
```

**Comment by alandmoore** [comment] 2017-10-24 18:40
Ah ok, I see.  This is fixed in devel branch but not in master.  In master, `list_devices` only checks that a device is usb and does not check for a partition table.

Can you switch to devel branch and see if the problem is fixed for you?

**Comment by malkavi** [comment] 2017-10-24 20:17
I have tested the devel branch and I can open and select a device. I still have to try to write isos.
Thanks!

**Comment by mbusb** [comment] 2017-11-19 10:13
Can some one test the new release and report back.

**Comment by malkavi** [comment] 2017-11-19 18:28
8.9.0 is working correctly.

**Closed** 2017-11-20 00:28 UTC
