### ISSUE TITLE
MBusb does not work with grml and persistence mode

### ISSUE THREAD

**Issue by fpusersuggest** [mbusb/multibootusb#232] opened 2017-11-15 18:01 UTC
Hi,
I have successfully installed grml sysadmin live cd on a mbusb. The problem is it does not work with persicence mode. I mean... I successul install the iso with enabled persistence space. I boot and it works well... but all data saved on the  home directory goes to deletion after reboot.

**Comment by thrdroom** [comment] 2018-03-12 11:29
This is a duplicate of #99

**Comment by mbusb** [comment] 2018-04-05 16:57
Latest release version 9.2.0 has fixed this debian persistence issue. Please check it out.

**Closed** 2018-04-06 05:53 UTC
