### ISSUE TITLE
USB only boots Grub Minimal Bash-Like

### ISSUE THREAD

**Issue by EnforcerZhukov** [mbusb/multibootusb#209] opened 2017-10-04 16:15 UTC
I installed a few Linux and Windows ISOs on a USB with MultiBootUSB. When I boot the usb, I just get this screen:

![image](https://user-images.githubusercontent.com/17401854/31186794-fb25ef1e-a92f-11e7-9741-3def14d74439.png)

Tried a second USB flash drive and installed just one ISO, and I'm getting the same screen,.

**Comment by openprivacy** [comment] 2017-10-18 13:38
Same issue with me after:
- installing kali-linux-2017.2-amd64.iso to a
- USB 3.0 stick /dev/sdb3 that was
- zeroed out then formatted FAT32

```
System:    Host: truckin Kernel: 4.13.7-1-ARCH x86_64 bits: 64 Desktop: N/A Distro: Arch Linux
Machine:   Device: laptop System: LENOVO product: 20F9CTO1WW v: ThinkPad T460s serial: N/A
           Mobo: LENOVO model: 20F9CTO1WW v: SDK0J40697 WIN serial: N/A
           UEFI: LENOVO v: N1CET47W (1.15 ) date: 08/08/2016
Drives:    HDD Total Size: 1065.2GB (46.4% used)
           ID-1: /dev/sda model: Samsung_SSD_850 size: 1000.2GB
           ID-2: USB /dev/sdb model: STORE_N_GO size: 65.0GB
```

**Comment by openprivacy** [comment] 2017-10-18 14:06
Hmmm... this is probably a duplicate of #186 (UEFI Boot Fails grub prompt)

**Comment by EnforcerZhukov** [comment] 2017-10-18 20:45
Well, It seems it might be the problem. I was trying on a new laptop, but I can't disable UEFI on it D:

Anyway, tried on an old laptop I have lying around and it booted ok. So, yeah, seems like the problem is with the UEFI, sadly.

**Comment by inthought** [comment] 2017-11-04 15:41
Also experiencing this issues on HP and Dell, both with UEFI. Changing to Legacy Bios works, but is not ideal and requires a BitLocker key on our setups.

**Comment by prudx** [comment] 2017-11-14 22:38
I have the same problem, also on a lenovo laptop. Not sure if that's anything to do with it. Changing to legacy works as a temp fix. Looking forward to next version :)

**Comment by mbusb** [comment] 2017-11-15 00:36
Can you test again using devel version...

**Comment by Honiix** [comment] 2017-11-20 15:04
I've the same problem. So I tried the devel branch.
What I did: 
- On Ubuntu 16.04.3 LTS I git cloned the repo.
- git checkout -b origin/devel
- sudo chmod +x ./install.py
- sudo ./install.py
Everything goes fine, but when I run /usr/local/bin/multibootusb I got the error:

> Traceback (most recent call last):
>  File "/usr/local/bin/multibootusb", line 164, in <module>
>    if config.debug is True:
> NameError: name 'config' is not defined

Is it the right way to test the devel version ?

**Comment by mbusb** [comment] 2017-11-20 16:46
Looks like you have installed multibootusb under python2 environment and multibootusb does not support python2. 

Instead of installing the source, directly run the program from source itself by using this command:-

```
cd /path/to/multibootusb/source/dir
sudo /usr/bin/python3 ./multibootusb
```

**Comment by mbusb** [comment] 2017-11-20 16:48
@Honiix 
Meanwhile, why don't you use the latest version 8.9.0. I just merged devel with master few days ago and released it to public.

**Comment by Honiix** [comment] 2017-11-20 22:19
@mbusb you're right, I should have thought about python 3.

I already tested the 8.9.0 and it gave me the grub prompt when trying to boot. I've tested so many things this morning that I can't give you a precise way to reproduce. As soon as I get the chance to test again, I'll get back here (probably thursday).

I've access to alot of laptops from HP and Lenovo. So if you need it, I can test many models with any configurations.

**Comment by mbusb** [comment] 2017-11-21 00:05
If the bootable USB fails to load and shows grub shell, can you type 'ls'
and post the output....

**Comment by Honiix** [comment] 2017-11-21 10:52
To reproduce I have to set the Lenovo to "UEFI only". With or without CSM, in both case I land on the GNU GRUB version 2.02~rc1 minimal Bash.

ls return: (proc)

**Comment by nerijus** [comment] 2017-11-28 14:06
I get (proc) too.

**Comment by rsprooten** [comment] 2017-12-03 22:26
Same issue using 8.9.0 on Windows 10.
The uput of ls is:
(ahci1) (ahci1,gpt3) (ahci1,gpt2) (ahci1,gpt1) (ahci0) (ahci0,gpt3) (ahci0,gpt2) (ahci0,gpt1) (ahci2) (proc)

the (proc) appears after a few seconds and the promt seems to hang.

**Comment by mbusb** [comment] 2017-12-05 00:21
Is your USB gpt?

**Comment by mbusb** [comment] 2018-01-07 05:57
Made new release with latest efi binary. Please check and report if same issue persist.

**Comment by mbusb** [comment] 2018-04-05 17:00
No one reported the same bug for a long time since last comment. Also, there has been many release with UEFI enhancement. Therefore I assume that the issue is solved.

**Closed by mbusb** 2018-04-05 17:00 UTC
