### ISSUE TITLE
option to list all drived is not working

### ISSUE THREAD

**Issue by Nemial** [mbusb/multibootusb#79] opened 2016-12-18 15:10 UTC
When you put it in the box the app crashes, makes an emergency stop

**Comment by mbusb** [comment] 2016-12-18 15:23
Please post the terminal output.

**Comment by Nemial** [comment] 2016-12-18 15:26
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/scripts/usb.py", line 361, in details
    udev = details_udev(usb_disk_part)
  File "/usr/lib/python3.4/site-packages/scripts/usb.py", line 220, in details_udev
    if not mount_point == '':
UnboundLocalError: local variable 'mount_point' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/scripts/mbusb_gui.py", line 105, in add_device
    self.onComboChange()
  File "/usr/lib/python3.4/site-packages/scripts/mbusb_gui.py", line 122, in onComboChange
    self.update_gui_oncombobox(config.usb_disk)
  File "/usr/lib/python3.4/site-packages/scripts/mbusb_gui.py", line 136, in update_gui_oncombobox
    self.usb_details = usb.details(usb_disk)
  File "/usr/lib/python3.4/site-packages/scripts/usb.py", line 372, in details
    udisks2 = details_udisks2(usb_disk_part)
  File "/usr/lib/python3.4/site-packages/scripts/usb.py", line 248, in details_udisks2
    mount_point = bd.Get('org.freedesktop.UDisks2.Filesystem', 'MountPoints', dbus_interface='org.freedesktop.DBus.Properties')
  File "/usr/lib/python3.4/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3.4/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.InvalidArgs: No such interface 'org.freedesktop.UDisks2.Filesystem'

**Comment by Nemial** [comment] 2016-12-18 15:40
And I Packed your program in the distribution of Rosa. And I need to know in this spec https://abf.rosalinux.ru/import/multibootusb/blob/rosa2016.1/multibootusb.spec I listed all the dependencies to work your program or not

**Comment by mbusb** [comment] 2016-12-18 15:44
I think you need to have 'p7zip-plugins' as well. I dont know why you have included 'python3-six'?

**Comment by Nemial** [comment] 2016-12-18 15:49
python3-six I included because without it it is not started. And is p7zip and p7zip-plugins is not the same?

**Comment by mbusb** [comment] 2016-12-18 15:51
multibootusb needs full version of 7zip (which has the support for ISO extraction support). I think ' p7zip-plugins' provides the full version of 7zip.

**Comment by Nemial** [comment] 2016-12-18 15:54
And as I understand the functionality of the program if I have a p7zip or not. It won't record images on a flash drive or what? Because all the specified functionality it performs with p7zip and it turns out nothing you turn on p7zip-plugins rpm in their assemblies

**Comment by mbusb** [comment] 2016-12-18 16:02
Here is the link to p7zip rpm:-
https://rpmfind.net/linux/RPM/fedora/devel/rawhide/aarch64/p/p7zip-16.02-2.fc26.aarch64.html
The list of files to be installed, as per the link, are:-
/usr/bin/**7za**
/usr/libexec/p7zip
/usr/libexec/p7zip/7zCon.sfx
/usr/libexec/p7zip/7za
/usr/share/doc/p7zip
/usr/share/doc/p7zip/7zC.txt
/usr/share/doc/p7zip/7zFormat.txt
/usr/share/doc/p7zip/ChangeLog
.
.
Clearly the above is a command line version of 7zip which does not have the support for ISO.

Here is the link to p7zip-plugins:
https://rpmfind.net/linux/RPM/fedora/devel/rawhide/aarch64/p/p7zip-plugins-16.02-2.fc26.aarch64.html
It says the following files will be installed:-
/usr/bin/**7z**
/usr/libexec/p7zip
/usr/libexec/p7zip/7z
/usr/libexec/p7zip/7z.so
/usr/share/doc/p7zip-plugins
/usr/share/doc/p7zip-plugins/contrib
/usr/share/doc/p7zip-plugins/contrib/VirtualFileSystemForMidnightCommander
/usr/share/doc/p7zip-plugins/contrib/VirtualFileSystemForMidnightCommander/ChangeLog
.
.
It says 7z will be installed which is wanted by multibootusb program. Hope this clarifies your doubt.

**Comment by Nemial** [comment] 2016-12-18 16:11
As I argued above, we have Rosa p7zip compiled with support for ISO. So the dependency p7zip-plugins are only needed for Fedora, so as soon as they did this separation of packages

**Comment by mbusb** [comment] 2016-12-18 16:17
Oh. I was not aware of this. Thanks for the clarification.

**Comment by Nemial** [comment] 2016-12-18 16:36
You're welcome. So I think you can in their assemblies rpm for magiea to make the dependence on instead of p7zip p7zip-plugins. Can this be used with my spec if you want

**Comment by mbusb** [comment] 2016-12-26 18:19
Fixed in the latest release. This is caused by the presence of 'Extended Partition".

**Closed by mbusb** 2016-12-26 18:19 UTC
