### ISSUE TITLE
Ubuntu Derivatives are not installing correctly

### ISSUE THREAD

**Issue by shawarkhan** [mbusb/multibootusb#76] opened 2016-12-07 07:32 UTC
I am not able to boot xubunutu or lubuntu created with multibootusb. The error says "not able to find live media" and this is after the initial boot screen of xubuntu, and the distro type it is detecting for xubuntu and lubuntu is "debian-install".

**Comment by mbusb** [comment] 2016-12-07 10:55
OK. Let me investigate it.

**Comment by mbusb** [comment] 2016-12-08 05:38
I am unable to reproduce your issue on my system. Tested Lubuntu and Xubuntu and working perfectly as expected. Which version of multibootusb are you using? Can you post your terminal output...

**Comment by mbusb** [comment] 2016-12-26 18:20
All working fine here. Therefore, closing the issue.

**Closed by mbusb** 2016-12-26 18:20 UTC
