### ISSUE TITLE
Syslinux install failure. Remounted as read only?

### ISSUE THREAD

**Issue by RlndVt** [mbusb/multibootusb#23] opened 2015-08-26 21:12 UTC
I put Elementary-OS freya i386 on a USB stick succesfully, but trying to put Ubuntu 15.04 i386 and(/or) Lubuntu 15.04 i386 it gets stuck on installing syslinux (0%). Running from terminal I get these error messages. 
````python
Updating main syslinux config file...
Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 298, in install_syslinux
    self.update_cfg_files.distro_cfg_files()
  File "/usr/lib/python2.7/dist-packages/scripts/update_cfg.py", line 171, in distro_cfg_files
    self.main_cfg_file()
  File "/usr/lib/python2.7/dist-packages/scripts/update_cfg.py", line 203, in main_cfg_file
    config_file = open(sys_cfg_file, "a")
IOError: [Errno 30] Read-only file system: '/media/roland/Ubuntu/multibootusb/syslinux.cfg'
````

Seems like the disk gets remounted RO just before it tries to execute this command.

Installed from deb file (7.5.0-1) on linuxmint 17.2

E:

I tried a new usb-stick and tried putting Ubuntu on first, but it got stuck at the same point again, whilst E-OS installed fine afterwards. (After removing and replacing the USB-Stick)

**Comment by RlndVt** [comment] 2015-08-31 21:20
My guess is it would have something to do with systemd, but it's a wild guess at that.

**Comment by mbusb** [comment] 2015-09-01 03:03
I tried to reproduce the same with kubuntu beta. But I could not get any error.

**Comment by Kopfgeldjaeger** [comment] 2015-09-02 11:37
I have the same problem. I'm on Ubuntu 15.04 x64.
After a few tries I successfully installed Ultimate Boot CD 5.3.5, but I can't get Lubuntu/Xubuntu/Ubuntu 15.04 to install because of this problem.

At one point I nearly had successfully installed Ubuntu 15.04, but it did not boot. The only difference that I noticed was that the ISO file had a space in its name ("ubuntu-15.04-desktop-amd64 (1).iso").

A few lines before the error appeared:
```
Copying chain.c32
Copying gfxboot.c32
Copying ldlinux.c32
Could not copy ldlinux.c32
Could not copy libcom32.c32
Could not copy libutil.c32
Could not copy vesamenu.c32
RRIP: rrip_offset 0
Updating main syslinux config file...
Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 298, in install_syslinux
    self.update_cfg_files.distro_cfg_files()
  File "/usr/lib/python2.7/dist-packages/scripts/update_cfg.py", line 171, in distro_cfg_files
    self.main_cfg_file()
  File "/usr/lib/python2.7/dist-packages/scripts/update_cfg.py", line 203, in main_cfg_file
    config_file = open(sys_cfg_file, "a")
IOError: [Errno 30] Das Dateisystem ist nur lesbar: '/media/nicolai/multiboot/multibootusb/syslinux.cfg'
```

Dmesg output:
```
[ 1968.043333] sd 8:0:0:0: Attached scsi generic sg3 type 0
[ 1969.846264] sd 8:0:0:0: [sdc] 30712320 512-byte logical blocks: (15.7 GB/14.6 GiB)
[ 1969.846485] sd 8:0:0:0: [sdc] Write Protect is off
[ 1969.846488] sd 8:0:0:0: [sdc] Mode Sense: 23 00 00 00
[ 1969.846705] sd 8:0:0:0: [sdc] No Caching mode page found
[ 1969.846707] sd 8:0:0:0: [sdc] Assuming drive cache: write through
[ 1969.869245]  sdc: sdc1
[ 1969.870617] sd 8:0:0:0: [sdc] Attached SCSI removable disk
[ 2277.521422] FAT-fs (sdc1): error, fat_free_clusters: deleting FAT entry beyond EOF
[ 2277.521425] FAT-fs (sdc1): Filesystem has been set read-only
```

Log with file renamed as "ubuntu-15.04-desktop-amd64 (1).iso":
```
Copying chain.c32
Copying gfxboot.c32
Copying ldlinux.c32
Could not copy ldlinux.c32
Copying libcom32.c32
Could not copy libcom32.c32
Copying libutil.c32
Could not copy libutil.c32
Copying vesamenu.c32
RRIP: rrip_offset 0
Updating main syslinux config file...
```

No dmesg error. Still won't boot (nothing happens after pressing menu entry).

After then removing the " (1)" in the folder name, editing syslinux.cfg, choosing "Syslinux -> "Install only syslinux", it works!

**Comment by mbusb** [comment] 2015-09-02 12:18
Thank you for the clarification.

**Comment by eridal** [comment] 2015-10-14 15:59
Same problem here.

I was able to install arch, antegros, and mint; but when I try to install ubuntu, or lubuntu, the drive filesystem ends up being marked as read-only, the installer fails, and the drive gets unusable.

have anybody found a workaround?

Here's the output:

    Using PyUdev for detecting USB drives...
    /dev/sdc1
    Cleaning old multibootusb directory.
    Extracting syslinux to multibootusb directory...
    Extracting syslinux 64 bit...
    Extracting syslinux modules to multibootusb directory...
    /usr/multibootusb/tools/syslinux/syslinux_modules.zip
    Copying persistence data to multibootusb directory.
    RRIP: rrip_offset 0
    ISO passed.
    Distro detected is ubuntu
    Persistence option is available.
    Persistence choosen is 256 MB
    RRIP: rrip_offset 0
    RRIP: rrip_offset 0
    Install dir is /media/martin/MultiBoot/multibootusb/ubuntu-15.04-desktop-amd64
    Distro extraction completed...
    RRIP: rrip_offset 0


    Found syslinux version 6


    distro_syslinux_install_dir is /multibootusb/ubuntu-15.04-desktop-amd64/isolinux
    distro_sys_install_bs is /media/martin/MultiBoot/multibootusb/ubuntu-15.04-desktop-amd64/isolinux/ubuntu.bs
    Executing ==> /home/martin/.multibootusb/syslinux/bin/syslinux6 -i -d /multibootusb/ubuntu-15.04-desktop-amd64/isolinux /dev/sdc1
    Syslinux install on distro directory is success...
    Executing ==> dd if=/dev/sdc1 of=/media/martin/MultiBoot/multibootusb/ubuntu-15.04-desktop-amd64/isolinux/ubuntu.bs count=1
    1+0 records in
    1+0 records out
    512 bytes (512 B) copied, 0,0026324 s, 194 kB/s

    Bootsector copy is success...

    RRIP: rrip_offset 0

    Executing ==> /home/martin/.multibootusb/syslinux/bin/syslinux4 -i -d multibootusb /dev/sdc1


    Default syslinux install is success...

    1+0 records in
    1+0 records out
    440 bytes (440 B) copied, 0,802249 s, 0,5 kB/s

    mbr install is success...

    Checking boot flag on /dev/sdc
    Disk /dev/sdc already has boot flag.
    RRIP: rrip_offset 0
    Applying Ubuntu patch...
    Copying chain.c32
    Copying gfxboot.c32
    Copying ldlinux.c32
    Could not copy ldlinux.c32
    Could not copy libcom32.c32
    Could not copy libutil.c32
    Could not copy vesamenu.c32
    RRIP: rrip_offset 0
    Updating main syslinux config file...
    Traceback (most recent call last):
      File "/usr/bin/multibootusb", line 298, in install_syslinux
        self.update_cfg_files.distro_cfg_files()
      File "/usr/lib/python2.7/dist-packages/scripts/update_cfg.py", line 171, in distro_cfg_files
        self.main_cfg_file()
      File "/usr/lib/python2.7/dist-packages/scripts/update_cfg.py", line 203, in main_cfg_file
        config_file = open(sys_cfg_file, "a")
    IOError: [Errno 30] Read-only file system: '/media/martin/MultiBoot/multibootusb/syslinux.cfg'

**Comment by eddy-geek** [comment] 2015-12-15 21:49
I found 2 workarounds:
* manually append the content of from multiboot/ubuntu.../syslinux/txt.cfg to multiboot/syslinux.cfg
* edit /usr/lib/python2.7/dist-packages/scripts/update_cfg.py before failing line to run command <"sudo mount -o remount,rw" + config.usb_disk> (I may post a patch if I find time)

**Comment by eridal** [comment] 2015-12-17 17:03
good stuff @eddy-geek . please PR!!

**Comment by gotnosocks** [comment] 2016-03-19 15:01
I just submitted pull request #44, using @eddy-geek's second workaround. Tested on master by installing ubuntu-gnome-15.10-desktop-amd64.iso from Fedora 23.

**Comment by milankni** [comment] 2016-04-26 17:05
Similar here. Arch Linux x86_64, trying to flash Ubuntu 16.04 x86_64:

dmesg reads:
`FAT-fs (sdd1): error, fat_free_clusters: deleting FAT entry beyond EOF`

and then FS becomes read-only.

```
Install dir is /run/media/mu/MK32GB/multibootusb/ubuntu-16.04-desktop-amd64
Distro extraction completed...
RRIP: rrip_offset 0


Found syslinux version 6


distro_syslinux_install_dir is /multibootusb/ubuntu-16.04-desktop-amd64/isolinux
distro_sys_install_bs is /run/media/mu/MK32GB/multibootusb/ubuntu-16.04-desktop-amd64/isolinux/ubuntu.bs
Executing ==> /home/mu/.multibootusb/syslinux/bin/syslinux6 -i -d /multibootusb/ubuntu-16.04-desktop-amd64/isolinux /dev/sdd1

Syslinux install on distro directory is success...

Executing ==> dd if=/dev/sdd1 of=/run/media/mu/MK32GB/multibootusb/ubuntu-16.04-desktop-amd64/isolinux/ubuntu.bs count=1

1+0 záznamů přečteno
1+0 záznamů zapsáno
512 bajtů zkopírováno, 0,0134911 s, 38,0 kB/s

Bootsector copy is success...
RRIP: rrip_offset 0
Executing ==> /home/mu/.multibootusb/syslinux/bin/syslinux4 -i -d multibootusb /dev/sdd1
Default syslinux install is success...
1+0 záznamů přečteno
1+0 záznamů zapsáno
440 bajtů zkopírováno, 0,00197192 s, 223 kB/s
mbr install is success...
Checking boot flag on /dev/sdd
Disk already has boot flag.
RRIP: rrip_offset 0
Applying Ubuntu patch...
Copying chain.c32
Copying gfxboot.c32
Copying ldlinux.c32
Could not copy ldlinux.c32
Could not copy libcom32.c32
Could not copy libutil.c32
Could not copy vesamenu.c32
RRIP: rrip_offset 0
Updating main syslinux config file...
Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 298, in install_syslinux
    self.update_cfg_files.distro_cfg_files()
  File "/usr/lib/python2.7/site-packages/scripts/update_cfg.py", line 171, in distro_cfg_files
    self.main_cfg_file()
  File "/usr/lib/python2.7/site-packages/scripts/update_cfg.py", line 203, in main_cfg_file
    config_file = open(sys_cfg_file, "a")
IOError: [Errno 30] Systém souborů je pouze pro čtení: '/run/media/mu/MK32GB/multibootusb/syslinux.cfg'

```

**Comment by mbusb** [comment] 2016-05-16 14:58
From the error log I can say that you guys are still testing with the release version of multibootusb (7.5.0). gotnosocks has fixed in  commit https://github.com/mbusb/multibootusb/pull/44. I have tested on ubuntu 14.04 and debian 8 with ununtu 16.04 iso.

Closing the issue.

**Closed by mbusb** 2016-05-16 14:58 UTC

**Comment by awisus** [comment] 2016-09-20 13:03
eddy-geek's hack (see https://github.com/gotnosocks/multibootusb/commit/a675d8165f26044872ccd33297f9032f7d0fc26f) may be working on Windows, but not on Linux.

Made a similar change on Ubuntu 16.04 (should be working on other OSs as well):

1. open /usr/lib/python2.7/dist-packages/scripts/update_cfg.py for editing
2. add on line 16: from subprocess import call
3. add on line 204: call(["mount", "-o", "remount,rw", config.usb_disk])
